on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

name: build and test

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y
          git
          bash
          cmake
          make
          g++
          python3-dev
          libatomic-ops-dev
          autoconf
          libgsl-dev
          zlib1g-dev
          libdeflate-dev
          libhts-dev
          samtools
          libjemalloc-dev
          bedtools
          cargo
      - name: Install wgatools
        run: cargo install --git https://github.com/wjwei-handsome/wgatools.git
      - name: Install pafcheck  
        run: cargo install --git https://github.com/ekg/pafcheck.git
      - name: Init and update submodules
        run: git submodule update --init --recursive
      - name: Build wfmash
        run: cmake -H. -Bbuild -D CMAKE_BUILD_TYPE=Debug -DWFA_PNG_AND_TSV=ON && cmake --build build -- -j 2
      - name: Run cmake tests
        run: |
          cd build
          ctest --output-on-failure
